; TILEZ.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 10
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

.SECTION Tiles

TileLabel:
.DB $00,$00,$00,$00,$00,$00,$00,$00
.DB $00,$00,$00,$00,$00,$00,$00,$00
.DB $28,$10,$00,$7C,$3A,$28,$3C,$02
.DB $14,$2C,$18,$28,$2E,$30,$02,$1C
.DB $00,$00,$3C,$20,$46,$78,$9F,$E0
.DB $64,$7A,$14,$38,$28,$34,$18,$10
.DB $24,$24,$3C,$3C,$3C,$6A,$3E,$FF
.DB $7E,$FF,$7F,$FF,$DB,$DB,$91,$91
.DB $9C,$E0,$AE,$D0,$C2,$BC,$C0,$FE
.DB $B2,$FE,$BC,$C0,$86,$F8,$86,$F8
.DB $C4,$FC,$BE,$E0,$E2,$DC,$C2,$FC
.DB $9C,$EC,$BE,$D0,$47,$B8,$C1,$FE
.DB $41,$3F,$E1,$1F,$53,$6F,$4D,$73
.DB $31,$3F,$71,$0F,$4D,$33,$81,$7F
.DB $41,$3F,$C3,$BD,$E1,$9F,$77,$4F
.DB $3F,$3F,$7D,$03,$41,$3F,$F3,$CF
.DB $7E,$00,$83,$7C,$81,$FE,$80,$FE
.DB $CA,$FE,$6E,$7E,$24,$3C,$58,$58
.DB $00,$00,$00,$00,$00,$00,$00,$00
.DB $00,$00,$00,$00,$00,$00,$00,$00
.DB $00,$00,$00,$00,$00,$00,$00,$00
.DB $00,$00,$00,$00,$00,$00,$00,$00

.ENDS
